version: '3'
services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ../library_back/.env
    ports:
      - "5432:5432"
    networks:
      - library-network
  
  backend:
    container_name: library_backend
    build: ../library_back
    restart: always
    depends_on:
      - db
    stdin_open: true
    ports:
      - '8001:8001'
    tty: true
    env_file:
      - ../library_back/.env
    networks:
      - library-network
  
  frontend:
    container_name: library_frontend
    build: ../library_front
    restart: always
    depends_on:
      - backend
    stdin_open: true
    ports:
      - '3000:3000'
    tty: true
    env_file:
      - ../library_front/.env
    networks:
      - library-network
  
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - library-network

networks:
  library-network: