version: '3'
services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - ../library_back/.env
    ports:
      - "5432:5432"