version: '3'
services:

  db:
    image: postgres:14.1-alpine
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
    ports:
      - "5432:5432"
    networks:
      - library-network
  
  backend:
    container_name: library_backend
    image: kadesh67/gces-library-backend:latest
    restart: always
    depends_on:
      - db
    stdin_open: true
    ports:
      - '8001:8001'
    tty: true
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
    networks:
      - library-network
  
  frontend:
    container_name: library_frontend
    image: kadesh67/gces-library-frontend:latest
    restart: always
    depends_on:
      - backend
    stdin_open: true
    ports:
      - '3000:3000'
    tty: true
    networks:
      - library-network
  
  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
    networks:
      - library-network

networks:
  library-network: