name: Publish Docker Images

on:
  workflow_run:
    workflows: [ "Test and Lint" ]
    types: 
      - completed

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
        run: cd app/library_back && heroku container:push -a eliseu-kadesh-library-backend web
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: cd app/library_back && heroku container:release -a eliseu-kadesh-library-frontend web

